### ISSUE TITLE
PHP notices

### ISSUE THREAD

**Issue by mudrd8mz** [EduardoKrausME/course_format_numeric#1]
I am experiencing a lot of PHP notices like

```
Notice: Undefined property: stdClass::$coursedisplay in course/format/numeric/lib.php on line 99
```

under Moodle 2.9

**Comment by mudrd8mz** [comment]
Not sure it is related but the section numbers in the timeline are wrong, too - see the screenshot.

![numeric](https://cloud.githubusercontent.com/assets/85831/9086897/bc45c584-3b87-11e5-88d7-21c7a318c2df.png)

**Comment by eduardokraus** [comment]
Done.

I forgot coursedisplay

https://github.com/EduardoKrausME/course_format_numeric/commit/e06f604d50f00cb528e5aba16ac5ce29bdd6cb6e#diff-828043dc9f8d10ccd58ff8b96297794fR313

**Comment by mudrd8mz** [comment]
Hi. I am still experiencing the following notice with a fresh new installation of the v1.3.1 version of the format, as is published in the Plugins directory:

```
Notice: Undefined property: stdClass::$coursedisplay in /course/format/renderer.php on line 779
```

Are you sure you have developer debugging display on?
